name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build and run unit tests with Maven
      run: mvn clean verify
      working-directory: GitHubActions

  sayHello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from sayHello"
      - name: Say goodbye
        run: echo "Goodbye from sayHello"
